### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by renatopp** [renatopp/behavior3js#1]
Self-explained

**Comment by elmarquez** [comment]
I've just submitted a pull request for the Bower configuration.  The package should then be registered with Bower, per the register instructions:

  http://bower.io/docs/creating-packages/

**Comment by renatopp** [comment]
Thanks @elmarquez! I'll probably take a look on this tomorrow.

**Comment by renatopp** [comment]
@elmarquez I've merged your changes and registered it to bower, but I'm not sure if it is working. Can you validate it?

**Comment by renatopp** [comment]
163aaaab129a8c70aa4d756649f38de7ec67d53c

**Comment by elmarquez** [comment]
Yes, its working.

> marques:tmp dmarques$ bower search behavior3js
> Search results:
> 
> behavior3js git://github.com/renatopp/behavior3js.git

> marques:tmp dmarques$ bower install -S behavior3js
> bower not-cached    git://github.com/renatopp/behavior3js.git#*
> bower resolve       git://github.com/renatopp/behavior3js.git#*
> bower download      https://github.com/renatopp/behavior3js/archive/0.1.0.tar.gz
> bower extract       behavior3js#* archive.tar.gz
> bower resolved      git://github.com/renatopp/behavior3js.git#0.1.0
> bower install       behavior3js#0.1.0

> marques:tmp dmarques$ ls -l vendor/behavior3js/
> total 32
> -rw-r--r--  1 dmarques  staff   405 Jan  7 00:45 CHANGES
> -rw-r--r--  1 dmarques  staff  1092 Jan  7 00:45 LICENSE
> -rw-r--r--  1 dmarques  staff  2740 Jan  7 00:45 README.rst
> -rw-r--r--  1 dmarques  staff   624 Jan  7 00:45 bower.json
> drwxr-xr-x  5 dmarques  staff   170 Jan  7 00:45 libs

> marques:tmp dmarques$ ls -l vendor/behavior3js/libs/
> total 232
> -rw-r--r--  1 dmarques  staff  88819 Jan  7 00:45 b3core.0.1.0.js
> -rw-r--r--  1 dmarques  staff  11776 Jan  7 00:45 b3core.0.1.0.min.js
> -rw-r--r--  1 dmarques  staff  14992 Jan  7 00:45 b3core.0.1.0.zip

**Comment by renatopp** [comment]
Cool! closing this. Thanks @elmarquez
