### ISSUE TITLE
What is the difference between parameters and properties?

### ISSUE THREAD

**Issue by FunkMonkey** [renatopp/behavior3js#10]
Maybe I am overlooking something, but I don't quite grasp the difference between `parameters` and `properties`, except that `parameters` are passed to the `initialize` function. The [docs](http://docs.guineashots.com/behavior3js/classes/BaseNode.html#property_parameters) did not really clear it up for me either and I could not find an example for using `properties` in the code...

What is the exact purpose of `properties` compared to `parameters`?

**Comment by renatopp** [comment]
What I was thinking when I created parameters and properties is:

**parameters** are only used in the node initialization, passed inside the `settings` parameter and discarded after the use. With this, the developer can specify the parameters default values in the node prototype and, thus, using them inside the editor.

**properties** can be any value that will be store in the node. I created this as a mechanism to define any variable the node would use, in the editor.

With your question, I see that parameters and properties are not really different, and could be merged into a single dictionary.

**Comment by renatopp** [comment]
Thinking about this, I came out with a resolution: **parameters should be read only**. It's means that, the user shouldn't be able to edit parameters inside the editor and the tree shouldn't read parameters from JSON.

Parameters are useful to tell the editor what variables a node needs in its initialization, such as the Wait node. They are also useful for default value in initialization (via JSON or programmatically).

Properties are the user-defined value, which can be modified inside the editor. Properties should replace parameters as arguments to the node initialization.

**Comment by renatopp** [comment]
Closed (see https://github.com/renatopp/behavior3editor/issues/2)
