### ISSUE TITLE
Re-architecture for the Editor

### ISSUE THREAD

**Issue by renatopp** [renatopp/behavior3js#13]
My initial idea was create a visual editor and debugger using the same base. In order to encapsulate the shared base I created the Viewer tool.

But, now I see that, the viewer and the editor have both a lot of dependencies and I don't want to couple these dependencies on the debugger. Thus, does not make sense anymore to have separate tools, one for editor and one for a base viewer.

Merging the two tools, I hope to have a better (and simpler) architecture, thus a improving the maintenance.

**Comment by renatopp** [comment]
Agreed, the first thing I'm gonna do is create an new repository for the editor. I'm currently working on a Python version of b3, for some experiments, and would be cool to keep things clear. 

Before any big change on the architecture, I'll simply merge both directories (there is only a few changes needed to do that). Since their folder structure are very similar, this change will be straightforward and will already help us in the build problem.

**Comment by grifdail** [comment]
Should the python version be in the same repo as the js version ?

2015-01-06 12:52 GMT+01:00 Renato de Pontes Pereira <
notifications@github.com>:

**Comment by renatopp** [comment]
No, I will create a new repository for the python version. Adding a new language port of b3 inside the current repository would create the need to add all other ports together, which I don't want.

I've already heard people porting b3 to game maker and java. I will add a link to all ports on the official page and to README in the repository.

**Comment by grifdail** [comment]
I may do a unity version if i need to use behavior tree in my unity
projects.

**Comment by renatopp** [comment]
I just created a new repository for the online editor: https://github.com/renatopp/behavior3editor

I am rewriting the editor right now, merging the viewer and the old editor, soon I will push the new version. 

I will close this for now, we can continue the discussion on the new repo.
