### ISSUE TITLE
How to Improve the Class Model?

### ISSUE THREAD

**Issue by renatopp** [renatopp/behavior3js#14]
Currently, we are using the `b3.Class` to create all classes related to behavior3js. But I don't know it this is really the best option. How could we improve this system?

**Comment by renatopp** [comment]
This isn't a priority right now, so I will keep this issue open for more discussion.

I don't like the idea of adding a dependence on b3 only to use the class/inheritance system. As @grifdail pointed out, the cost of this would be bigger than the benefits.

**Comment by FunkMonkey** [comment]
Even though it would only be a new grunt-build-dependency, I agree it may be overkill for inheritance only (unless you want to use other es6-features and even then only the features that don't need the runtime-shim make sense).
