### ISSUE TITLE
How to check  condition

### ISSUE THREAD

**Issue by cq-z** [renatopp/behavior3js#16]
How to add condition and check  condition？

**Comment by cq-z** [comment]
Whether in Composite Nodes add  addCondition and CheckCondition method？

**Comment by renatopp** [comment]
Hi, @cq-z 

Just create a Condition node,

    var MyCondition = b3.Class(b3.Condition);
    MyCondition.prototype.name = "MyCondition";
    MyCondition.prototype.tick = function() {
        return CONDITION === CONDITION;
    }

Do not add any kind of condition in Composite nodes.

I'm closing this now. If necessary, feel free to reopen.

**Comment by cq-z** [comment]
thank you!

**Comment by cq-z** [comment]
HI @renatopp 
me behavior3js translate to PHP （https://github.com/cq-z/behavior3js/tree/php/src）
Please advice

**Comment by renatopp** [comment]
Cool @cq-z 

I recommend that you port tests too, so you can be sure that everything is working as expected.
